AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: SAM config for Tweeter server


#
# Global Lambda function properties. These apply to every Lambda function.
#
Globals:
  Function:
    Runtime: nodejs20.x
    CodeUri: ./dist/
    Layers:
      - !Ref tweeterLayer
    Timeout: 30
    MemorySize: 128


#
# Reusable blocks of configuration. These are referenced throughout the template to avoid duplication.
# &identifier is used to define a reusable block, and *identifier is used to reference it.
#
Metadata:
  x-common-policies: &commonPolicies
    - AWSLambdaBasicExecutionRole
    - AmazonSESFullAccess
    - CloudWatchFullAccess
    - AmazonDynamoDBFullAccess
    - AmazonS3FullAccess
    - AmazonSQSFullAccess

  x-common-cors-headers: &commonCorsHeaders
    method.response.header.Access-Control-Allow-Origin: "'*'"

  x-common-swagger-response-headers: &commonSwaggerResponseHeaders
    Access-Control-Allow-Origin:
      type: string


#
# AWS resource definitions
#
Resources:


  #
  # Web API
  #


  tweeterApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: tweeterApi
      StageName: prod
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
      DefinitionBody:
        swagger: "2.0"
        info:
          title: "Tweeter API"
          version: "1.0"
        x-common-consumes: &commonConsumes
          - application/json
        x-common-produces: &commonProduces
          - application/json
        x-common-request-templates: &commonRequestTemplates
          application/json: $input.json('$')
        x-common-amazon-responses: &commonAmazonResponses
          default:
            statusCode: 200
            responseParameters: *commonCorsHeaders
          ".*bad-request.*":
            statusCode: 400
            responseParameters: *commonCorsHeaders
            responseTemplates:
              application/json: '{ "error": "$input.path(''$.errorMessage'')" }'
          ".*unauthorized.*":
            statusCode: 401
            responseParameters: *commonCorsHeaders
            responseTemplates:
              application/json: '{ "error": "$input.path(''$.errorMessage'')" }'
          ".*internal-server-error.*":
            statusCode: 500
            responseParameters: *commonCorsHeaders
            responseTemplates:
              application/json: '{ "error": "$input.path(''$.errorMessage'')" }'
        x-common-swagger-responses: &commonSwaggerResponses
          "200":
            description: "OK"
            headers: *commonSwaggerResponseHeaders
          "400":
            description: "Bad Request"
            headers: *commonSwaggerResponseHeaders
          "401":
            description: "Unauthorized"
            headers: *commonSwaggerResponseHeaders
          "500":
            description: "Internal Server Error"
            headers: *commonSwaggerResponseHeaders
        paths:

          #
          # Endpoint definitions
          #

          /followees:
            post:
              consumes: *commonConsumes
              produces: *commonProduces
              x-amazon-apigateway-integration:
                type: aws
                httpMethod: POST
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${getFollowees.Arn}/invocations
                requestTemplates: *commonRequestTemplates
                responses: *commonAmazonResponses
              responses: *commonSwaggerResponses

          /followers:
            post:
              consumes: *commonConsumes
              produces: *commonProduces
              x-amazon-apigateway-integration:
                type: aws
                httpMethod: POST
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${getFollowers.Arn}/invocations
                requestTemplates: *commonRequestTemplates
                responses: *commonAmazonResponses
              responses: *commonSwaggerResponses

          /follow_status:
            post:
              consumes: *commonConsumes
              produces: *commonProduces
              x-amazon-apigateway-integration:
                type: aws
                httpMethod: POST
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${getFollowStatus.Arn}/invocations
                requestTemplates: *commonRequestTemplates
                responses: *commonAmazonResponses
              responses: *commonSwaggerResponses

          /follow:
            post:
              consumes: *commonConsumes
              produces: *commonProduces
              x-amazon-apigateway-integration:
                type: aws
                httpMethod: POST
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CreateFollow.Arn}/invocations
                requestTemplates: *commonRequestTemplates
                responses: *commonAmazonResponses
              responses: *commonSwaggerResponses

          /unfollow:
            post:
              consumes: *commonConsumes
              produces: *commonProduces
              x-amazon-apigateway-integration:
                type: aws
                httpMethod: POST
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DeleteFollow.Arn}/invocations
                requestTemplates: *commonRequestTemplates
                responses: *commonAmazonResponses
              responses: *commonSwaggerResponses

          /followees/count:
            post:
              consumes: *commonConsumes
              produces: *commonProduces
              x-amazon-apigateway-integration:
                type: aws
                httpMethod: POST
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetFolloweeCount.Arn}/invocations
                requestTemplates: *commonRequestTemplates
                responses: *commonAmazonResponses
              responses: *commonSwaggerResponses

          /followers/count:
            post:
              consumes: *commonConsumes
              produces: *commonProduces
              x-amazon-apigateway-integration:
                type: aws
                httpMethod: POST
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetFollowerCount.Arn}/invocations
                requestTemplates: *commonRequestTemplates
                responses: *commonAmazonResponses
              responses: *commonSwaggerResponses

          /post:
            post:
              consumes: *commonConsumes
              produces: *commonProduces
              x-amazon-apigateway-integration:
                type: aws
                httpMethod: POST
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CreateStatus.Arn}/invocations
                requestTemplates: *commonRequestTemplates
                responses: *commonAmazonResponses
              responses: *commonSwaggerResponses

          /feed:
            post:
              consumes: *commonConsumes
              produces: *commonProduces
              x-amazon-apigateway-integration:
                type: aws
                httpMethod: POST
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetFeedStatuses.Arn}/invocations
                requestTemplates: *commonRequestTemplates
                responses: *commonAmazonResponses
              responses: *commonSwaggerResponses

          /story:
            post:
              consumes: *commonConsumes
              produces: *commonProduces
              x-amazon-apigateway-integration:
                type: aws
                httpMethod: POST
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetStoryStatuses.Arn}/invocations
                requestTemplates: *commonRequestTemplates
                responses: *commonAmazonResponses
              responses: *commonSwaggerResponses

          /login:
            post:
              consumes: *commonConsumes
              produces: *commonProduces
              x-amazon-apigateway-integration:
                type: aws
                httpMethod: POST
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CreateAuth.Arn}/invocations
                requestTemplates: *commonRequestTemplates
                responses: *commonAmazonResponses
              responses: *commonSwaggerResponses

          /logout:
            post:
              consumes: *commonConsumes
              produces: *commonProduces
              x-amazon-apigateway-integration:
                type: aws
                httpMethod: POST
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DeleteAuth.Arn}/invocations
                requestTemplates: *commonRequestTemplates
                responses: *commonAmazonResponses
              responses: *commonSwaggerResponses

          /register:
            post:
              consumes: *commonConsumes
              produces: *commonProduces
              x-amazon-apigateway-integration:
                type: aws
                httpMethod: POST
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CreateUser.Arn}/invocations
                requestTemplates: *commonRequestTemplates
                responses: *commonAmazonResponses
              responses: *commonSwaggerResponses

          /user:
            post:
              consumes: *commonConsumes
              produces: *commonProduces
              x-amazon-apigateway-integration:
                type: aws
                httpMethod: POST
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetUser.Arn}/invocations
                requestTemplates: *commonRequestTemplates
                responses: *commonAmazonResponses
              responses: *commonSwaggerResponses

  #
  # SQS Queues  (This will become relevant in Milestone 4. For M3, leave this section commented out.)
  #

  #   MyQueue:
  #     Type: AWS::SQS::Queue
  #     Properties:
  #       QueueName: MyQueue


  #
  # Lambda Layer (reused by all Lambda functions)
  #

  tweeterLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: tweeterLayer
      Description: dependencies layer for Tweeter server
      ContentUri: ./layer/
      CompatibleRuntimes:
        - nodejs20.x
      RetentionPolicy: DELETE


  #
  # Web API Lambda functions
  #

  getFollowees:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getFollowees
      Handler: lambda/follows/GetFollowees.handler
      Policies: *commonPolicies
      Events:
        PostApi:
          Type: Api
          Properties:
            RestApiId: !Ref tweeterApi
            Path: /followees
            Method: POST

  getFollowers:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getFollowers
      Handler: lambda/follows/GetFollowers.handler
      Policies: *commonPolicies
      Events:
        PostApi:
          Type: Api
          Properties:
            RestApiId: !Ref tweeterApi
            Path: /followers
            Method: POST

  getFollowStatus:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getFollowStatus
      Handler: lambda/follows/GetFollowStatus.handler
      Policies: *commonPolicies
      Events:
        PostApi:
          Type: Api
          Properties:
            RestApiId: !Ref tweeterApi
            Path: /follow_status
            Method: POST

  CreateFollow:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: CreateFollow
      Handler: lambda/follows/CreateFollow.handler
      Policies: *commonPolicies
      Events:
        PostApi:
          Type: Api
          Properties:
            RestApiId: !Ref tweeterApi
            Path: /follow
            Method: POST

  DeleteFollow:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: DeleteFollow
      Handler: lambda/follows/DeleteFollow.handler
      Policies: *commonPolicies
      Events:
        PostApi:
          Type: Api
          Properties:
            RestApiId: !Ref tweeterApi
            Path: /unfollow
            Method: POST

  GetFolloweeCount:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GetFolloweeCount
      Handler: lambda/follows/GetFolloweeCount.handler
      Policies: *commonPolicies
      Events:
        PostApi:
          Type: Api
          Properties:
            RestApiId: !Ref tweeterApi
            Path: /followees/count
            Method: POST

  GetFollowerCount:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GetFollowerCount
      Handler: lambda/follows/GetFollowerCount.handler
      Policies: *commonPolicies
      Events:
        PostApi:
          Type: Api
          Properties:
            RestApiId: !Ref tweeterApi
            Path: /followers/count
            Method: POST

  CreateStatus:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: CreateStatus
      Handler: lambda/status/CreateStatus.handler
      Policies: *commonPolicies
      Events:
        PostApi:
          Type: Api
          Properties:
            RestApiId: !Ref tweeterApi
            Path: /post
            Method: POST

  GetFeedStatuses:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GetFeedStatuses
      Handler: lambda/status/GetFeedStatuses.handler
      Policies: *commonPolicies
      Events:
        PostApi:
          Type: Api
          Properties:
            RestApiId: !Ref tweeterApi
            Path: /feed
            Method: POST

  GetStoryStatuses:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GetStoryStatuses
      Handler: lambda/status/GetStoryStatuses.handler
      Policies: *commonPolicies
      Events:
        PostApi:
          Type: Api
          Properties:
            RestApiId: !Ref tweeterApi
            Path: /story
            Method: POST

  CreateAuth:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: CreateAuth
      Handler: lambda/users/CreateAuth.handler
      Policies: *commonPolicies
      Events:
        PostApi:
          Type: Api
          Properties:
            RestApiId: !Ref tweeterApi
            Path: /login
            Method: POST

  DeleteAuth:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: DeleteAuth
      Handler: lambda/users/DeleteAuth.handler
      Policies: *commonPolicies
      Events:
        PostApi:
          Type: Api
          Properties:
            RestApiId: !Ref tweeterApi
            Path: /logout
            Method: POST

  CreateUser:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: CreateUser
      Handler: lambda/users/CreateUser.handler
      Policies: *commonPolicies
      Events:
        PostApi:
          Type: Api
          Properties:
            RestApiId: !Ref tweeterApi
            Path: /register
            Method: POST

  GetUser:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GetUser
      Handler: lambda/users/GetUser.handler
      Policies: *commonPolicies
      Events:
        PostApi:
          Type: Api
          Properties:
            RestApiId: !Ref tweeterApi
            Path: /user
            Method: POST
  #
  # Domain Configuration
  #

  ApiCustomDomain:
    Type: AWS::ApiGateway::DomainName
    Properties:
      DomainName: tweeter-api.dbl00m11.click
      RegionalCertificateArn: arn:aws:acm:us-west-2:385027548295:certificate/ca383c7c-c620-4495-b353-b1809bcf02f8
      EndpointConfiguration:
        Types:
          - REGIONAL

  ApiBasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      DomainName: !Ref ApiCustomDomain
      RestApiId: !Ref tweeterApi
      Stage: prod